name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: python -m pip install --upgrade pip

      - name: run feather script
        run: python feather.py clean build javadocJar checkMappings mapNamedJar 1.3 1.4 1.5 1.6 1.7 1.8 1.9 1.10 1.11 1.12
