name: Build
on: [ workflow_dispatch, push ]
jobs:
  matrix_prep:
    uses: ./.github/workflows/matrix_prep.yml

  build:
    needs: matrix_prep
    runs-on: ubuntu-22.04

    strategy:
      max-parallel: 5
      matrix: ${{ fromJson(needs.matrix_prep.outputs.versions) }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: run build script
        run: python3 build_all.py
        env:
          MC_VERSIONS: ${{ join(matrix.version_range, ',') }}