name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 20
      matrix:
        version: ["a1.0.1_01", "a1.1.0", "a1.2.0", "a1.2.6", "b1.0", "b1.2", "b1.5", "b1.6", "b1.7", "b1.8", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11", "1.12", "1.13"]
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: python -m pip install --upgrade pip

      - name: run feather script
        run: python feather.py clean build javadocJar checkMappings mapNamedJar ${{ matrix.version }}
