name: Publish
on: [ workflow_dispatch ]
jobs:
  matrix_prep:
    uses: ./.github/workflows/matrix_prep.yml

  display_versions:
    needs: matrix_prep
    runs-on: ubuntu-22.04
    steps:
      - name: display versions
        run: echo '${{ needs.matrix_prep.outputs.versions }}' | jq '.include[].version_range[]'

  build:
    needs: matrix_prep
    runs-on: ubuntu-22.04

    strategy:
      max-parallel: 20
      matrix: ${{ fromJson(needs.matrix_prep.outputs.versions) }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: run publish script
        run: python3 publish.py
        env:
          MC_VERSIONS: ${{ join(matrix.version_range, ',') }}
          MAVEN_URL: ${{ secrets.NEW_MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.NEW_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEW_MAVEN_PASSWORD }}